---
title: "gene_exp_analysis1"
date: '2023-06-26'
output: html_document
---

```{r}
require(DESeq2)
require('biomaRt')
require(survival)
require(data.table)
library(EnhancedVolcano)
library(ggplot2)
library(ggfortify)
library(scales)
library(haven)
library(nnet)
library(simstudy)
library(magrittr)
library(class)
library(dplyr)
```

This part, I loading the raw htseq-count of transcriptomic data, convert it to read count data and write it to a file.
```{r reading transcriptomic data}
gene.exp <- read.table("../data/TCGA-BLCA.htseq_counts.tsv.gz",
                     header = TRUE,sep = "\t",stringsAsFactors = FALSE)
#colnames(gene.exp) <- gsub("\\.","-",colnames(gene.exp))
gene.exp <- gene.exp[grepl("ENS", gene.exp$Ensembl_ID), ]
gene.exp <- gene.exp[, order(names(gene.exp))]

genecode.id <- gene.exp[,1]
fixed_names <- sapply(strsplit(genecode.id, ".", fixed=T), function(x) x[1])

gene.exp[,1] <- fixed_names

row.names(gene.exp) <- gene.exp[,1]
gene.exp <- gene.exp[-1]
gene.exp <- 2^gene.exp -1
gene.exp <- subset(gene.exp, !(rowSums(gene.exp < 5) == ncol(gene.exp)))

genes.arr <- row.names(gene.exp) #name of genes
write.table(gene.exp, file = "../results/gene_exp_analysis/count_data.csv", sep = "\t", quote = FALSE, row.names = TRUE)
gene.exp <- as.data.frame(lapply(gene.exp, as.integer))
```

```{r reading clinical data}
clin.data <- read.csv("../data/TCGA-BLCA.survival.tsv",
                      header = TRUE,sep = "\t",stringsAsFactors = FALSE)

clin.data <- clin.data[order(clin.data$sample), ]
clin.data$sample <- gsub("\\-",".",clin.data$sample)
```

```{r reading phenotype data}
phenotype <- read.csv("../data/TCGA-BLCA.GDC_phenotype.tsv.gz",header=TRUE,sep="\t")
phenotype <- phenotype[order(phenotype$submitter_id.samples), ]
phenotype$submitter_id.samples <- gsub("\\-",".",phenotype$submitter_id.samples)
```

Clinical data including stage of patient is here.
```{r Preprocess data}
overlapped.samples <- colnames(gene.exp) #samples from transcriptomic data
clin.data <- clin.data[clin.data$sample %in% overlapped.samples, ]
phenotype <- phenotype[phenotype$submitter_id.samples %in% clin.data$sample, ]
phenotype <- phenotype[!grepl("not reported", phenotype$tumor_stage.diagnoses), ]

gene.exp <- gene.exp[,phenotype$submitter_id.samples]
clin.data <- clin.data[clin.data$sample %in% phenotype$submitter_id.samples, ]
phenotype$tumor_stage.diagnoses <- factor(phenotype$tumor_stage.diagnoses, levels = c("stage i", "stage ii", "stage iii", "stage iv"))
phenotype$tumor_stage.diagnoses <- as.numeric(phenotype$tumor_stage.diagnoses)
clin.data$stage <- phenotype$tumor_stage.diagnoses
write.table(clin.data, file = "../results/gene_exp_analysis/clinical.csv", sep = "\t", quote = FALSE, row.names = FALSE)

```

```{r Deseq2 without stage}
dds <- DESeqDataSetFromMatrix(countData=gene.exp,
                              colData=DataFrame(OS=as.factor(clin.data$OS)),
                              design=~OS
)
dds <- estimateSizeFactors(dds)
dds <- DESeq(dds)
res <- results(dds)
```
```{r}
res$gene <- genes.arr
res
```

```{r Deseq2 with all stages}
dds_stage <- DESeqDataSetFromMatrix(countData=gene.exp,
                              colData=DataFrame(OS=as.factor(clin.data$OS),stage=as.factor(clin.data$stage)),
                              design=~OS
)
dds_stage <- estimateSizeFactors(dds_stage)
dds_stage <- DESeq(dds_stage)
res_stage <- results(dds_stage)
```

```{r get significant genes}
sig_indices <-which(res$padj < 0.01 & (res$log2FoldChange < -1 | res$log2FoldChange > 1))
sig_indices_stage <-which(res_stage$padj < 0.01 & (res_stage$log2FoldChange < -1 | res_stage$log2FoldChange > 1))
######
normalizedCounts_stage <- as.data.frame(counts(dds_stage, normalized = TRUE))
normalizedCounts <- as.data.frame(counts(dds, normalized = TRUE))
rawCounts <- as.data.frame(counts(dds, normalized = FALSE))
#####
normalizedCounts_stage$genes <- genes.arr
normalizedCounts$genes <- genes.arr
rawCounts$genes <- genes.arr
#####
significantGenes_stage <- normalizedCounts_stage[sig_indices_stage,]
significantGenes <- normalizedCounts[sig_indices,]
significantGenes_raw <- rawCounts[sig_indices,]
```

```{r biomart + cnv}
cnv_final <- read.csv("../results/cnv_analysis/final_cnv.csv",stringsAsFactors=FALSE, header=TRUE)

mart <- useMart('ENSEMBL_MART_ENSEMBL')
mart <- useDataset('hsapiens_gene_ensembl', mart)

annotLookup <- getBM(
  mart = mart,
  attributes = c(
    'hgnc_symbol',
    'ensembl_gene_id',
    'gene_biotype'),
  uniqueRows = TRUE)
head(annotLookup)
filt.annotLookup <- subset(annotLookup, hgnc_symbol != '')
```

```{r get overlapped genes of CNV and transcriptomic analysis}
matched.genes <- filt.annotLookup[filt.annotLookup$hgnc_symbol %in% cnv_final$GeneSymbol, ]
cnv_genes_exp <- which(significantGenes$genes %in% matched.genes$ensembl_gene_id)
cnv_gene_raw <- which(significantGenes_raw$genes %in% matched.genes$ensembl_gene_id)
cnv_genes_exp_stage <- which(significantGenes_stage$genes %in% matched.genes$ensembl_gene_id)
```

```{r nhap}
sig_genes_ann <- matched.genes[which(matched.genes$ensembl_gene_id %in% significantGenes$genes),]
sig_genes_ann_stage <- matched.genes[which(matched.genes$ensembl_gene_id %in% significantGenes_stage$genes),]
```

```{r final data for training}
significantGenes_cnv <- significantGenes[cnv_genes_exp,]
significantGenes_cnv_raw <- significantGenes_raw[cnv_gene_raw,]
significantGenes_cnv_stage <- significantGenes_stage[cnv_genes_exp_stage,]
write.table(significantGenes_cnv, file = "../results/gene_exp_analysis/cnv_genes_exp.combine.csv", sep = "\t", quote = FALSE, row.names = FALSE)
write.table(significantGenes_cnv_stage, file = "../results/gene_exp_analysis/cnv_genes_exp_stage.combine.csv", sep = "\t", quote = FALSE, row.names = FALSE)
write.table(significantGenes_cnv_raw, file = "../results/gene_exp_analysis/cnv_genes_exp_raw.combine.csv", sep = "\t", quote = FALSE, row.names = FALSE)
```

# Survival Analysis
```{r multivariate cox hazard model}
significantGenes_cnv <- read.csv("../results/gene_exp_analysis/cnv_genes_exp_raw.combine.csv",header=T,sep="\t")
clin.data <- read.csv("../results/gene_exp_analysis/clinical.csv",header=T,sep="\t")
all_genes <- significantGenes_cnv$genes
gene_expression <- significantGenes_cnv[,-ncol(significantGenes_cnv)]
row.names(gene_expression) <- all_genes
gene_expression <- t(gene_expression)
survival_data <- clin.data
rownames(survival_data) <- survival_data$sample
merged_data <- merge(gene_expression, survival_data, by = "row.names",all = TRUE)
surv_obj <- with(merged_data, Surv(OS.time, OS))
cox_model <- coxph(surv_obj ~ . - Row.names - sample - X_PATIENT - OS - OS.time - stage, data = merged_data)
```

```{r}
summary(cox_model)
```

```{r}
sfit <- survfit(Surv(OS.time, OS)~ stage, data=merged_data, type = "kaplan-meier", 
            conf.type = "log")
autoplot(sfit, conf.int = F, main="Kaplan-Meier-estimate")
```
```{r}
gene_id <- c("ENSG00000184697","ENSG00000237412","ENSG00000265787","ENSG00000277586","ENSG00000121871")
row.names(matched.genes) <- matched.genes$ensembl_gene_id
matched.genes[gene_id,]
```